# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "86ae39dc952b8517992793837a49b4d5"
name = "Chicago App"
application_url = "https://cole-acoustic-mapping-pumps.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://cole-acoustic-mapping-pumps.trycloudflare.com/auth/callback"
]
