# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dacb5708bcc1fb43e3205f0412e66d9e"
name = "Chicago Product App"
application_url = "https://chicagoprint-pros.vercel.app/"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://chicagoprint-pros.vercel.app/auth/callback" ]
